export enum Permission {
  DEPOSITS_MANAGE = 'deposits.manage',
  WITHDRAWALS_MANAGE = 'withdrawals.manage',
  USERS_MANAGE = 'users.manage',
  BUSINESS_MANAGE = 'business.manage',
  COMMISSIONS_MANAGE = 'commissions.manage',
  INVESTORS_MANAGE = 'investors.manage',
  SUPPORT_MANAGE = 'support.manage',
  PAYMENT_CONFIG_MANAGE = 'payment_config.manage',
  PLATFORM_SETTINGS_MANAGE = 'platform_settings.manage',
  AUDIT_VIEW = 'audit.view',
  WALLET_ADJUST = 'wallet.adjust',
  BUSINESS_DEPOSIT_VERIFY = 'business.deposit_verify',
  BUSINESS_WITHDRAWALS = 'business.withdrawals',
  BUSINESS_MANUAL_WITHDRAWAL = 'business.manual_withdrawal',
  /** Sub-admin may open panel as end-user / investor / business owner. */
  LOGIN_AS_USER = 'login_as.user',
  LOGIN_AS_INVESTOR = 'login_as.investor',
  LOGIN_AS_BUSINESS = 'login_as.business',
}
