export const PERMISSIONS = {
  DEPOSITS: 'deposits.manage',
  WITHDRAWALS: 'withdrawals.manage',
  USERS: 'users.manage',
  BUSINESS: 'business.manage',
  COMMISSIONS: 'commissions.manage',
  SUPPORT: 'support.manage',
  PAYMENT_CONFIG: 'payment_config.manage',
  AUDIT: 'audit.view',
  WALLET: 'wallet.adjust',
  PLATFORM_SETTINGS: 'platform_settings.manage',
  LOGIN_AS_USER: 'login_as.user',
  LOGIN_AS_INVESTOR: 'login_as.investor',
  LOGIN_AS_BUSINESS: 'login_as.business',
} as const;
